import { drizzle } from 'drizzle-orm/libsql';
import { createClient } from '@libsql/client';
import * as schema from './schema';
import { hashPassword } from '../lib/auth';
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });
dotenv.config();

const client = createClient({
  url: process.env.DATABASE_URL || 'file:local.db',
  authToken: process.env.DATABASE_AUTH_TOKEN || undefined,
});
const db = drizzle(client, { schema });

/* ------------------------------------------------------------------ locations */
const WAREHOUSES = [
  {
    id: 'BLR-STORE',
    name: 'Bengaluru Flagship Store',
    city: 'Bengaluru, KA',
    staff: 6,
    capacity: 0.72,
  },
  { id: 'HYD-STORE', name: 'Hyderabad Store', city: 'Hyderabad, TS', staff: 4, capacity: 0.55 },
  { id: 'BLR-STOCK', name: 'Central Stockroom', city: 'Bengaluru, KA', staff: 3, capacity: 0.48 },
];

/* ------------------------------------------------------------------ suppliers */
const SUPPLIERS = [
  {
    id: 's1',
    name: 'Auraluxe Candles',
    contact: 'Ananya Rao',
    email: 'ananya@auraluxe.in',
    phone: '+91 80 4123 5567',
    onTime: 0.96,
    lastOrder: 'Jul 12',
    spend: 148200,
  },
  {
    id: 's2',
    name: 'Kastoori Crafts',
    contact: 'Imran Sheikh',
    email: 'imran@kastoori.in',
    phone: '+91 141 220 8890',
    onTime: 0.91,
    lastOrder: 'Jul 09',
    spend: 96400,
  },
  {
    id: 's3',
    name: 'Cocoa Grove Foods',
    contact: 'Neha Kapoor',
    email: 'neha@cocoagrove.in',
    phone: '+91 22 4008 1123',
    onTime: 0.88,
    lastOrder: 'Jul 15',
    spend: 132900,
  },
  {
    id: 's4',
    name: 'Mysore Naturals',
    contact: 'Suresh Kumar',
    email: 'suresh@mysorenaturals.in',
    phone: '+91 821 244 5566',
    onTime: 0.94,
    lastOrder: 'Jul 05',
    spend: 78600,
  },
  {
    id: 's5',
    name: 'Papertrail Studio',
    contact: 'Divya Nair',
    email: 'divya@papertrail.in',
    phone: '+91 44 2811 3344',
    onTime: 0.97,
    lastOrder: 'Jul 14',
    spend: 54300,
  },
  {
    id: 's6',
    name: 'Glowveda Lights',
    contact: 'Arjun Patel',
    email: 'arjun@glowveda.in',
    phone: '+91 79 4002 7788',
    onTime: 0.9,
    lastOrder: 'Jul 11',
    spend: 61250,
  },
];

/* ------------------------------------------------------------------- products
 * Gift-shop catalogue. Prices in ₹. Gift attributes (occasions/recipients/age/
 * types/interests) power the storefront Gift Finder. Media is attached below in
 * PRODUCT_MEDIA (real photos + a few short videos live in public/seed/). */
const PRODUCTS = [
  {
    id: 'p1',
    name: 'Vanilla Bean Soy Candle',
    sku: 'AUR-CND-001',
    barcode: '8901111000011',
    category: 'Candles',
    brand: 'Auraluxe',
    price: 649,
    cost: 288,
    stock: 120,
    reserved: 8,
    incoming: 60,
    damaged: 1,
    warehouse: 'BLR-STORE',
    supplier: 'Auraluxe Candles',
    status: 'active',
    tag: 'Bestseller',
    hsnCode: '3406',
    gstRate: 12,
    giftOccasions: 'birthday,anniversary,housewarming,thank-you',
    giftRecipients: 'women,anyone',
    giftAgeMin: null,
    giftAgeMax: null,
    giftTypes: 'home-decor',
    giftInterests: 'aromatherapy,relaxation,home',
  },
  {
    id: 'p2',
    name: 'Rose Gold Photo Frame',
    sku: 'MEM-FRM-004',
    barcode: '8901111000028',
    category: 'Home Decor',
    brand: 'Memoirs',
    price: 899,
    cost: 402,
    stock: 46,
    reserved: 2,
    incoming: 0,
    damaged: 0,
    warehouse: 'BLR-STORE',
    supplier: 'Kastoori Crafts',
    status: 'active',
    tag: null,
    hsnCode: '8306',
    gstRate: 12,
    giftOccasions: 'wedding,anniversary,housewarming',
    giftRecipients: 'anyone',
    giftAgeMin: null,
    giftAgeMax: null,
    giftTypes: 'photo-frame,home-decor',
    giftInterests: 'memories,photography,home',
  },
  {
    id: 'p3',
    name: 'Handcrafted Jewelry Box',
    sku: 'KAS-JWB-012',
    barcode: '8901111000035',
    category: 'Home Decor',
    brand: 'Kastoori',
    price: 1499,
    cost: 675,
    stock: 18,
    reserved: 1,
    incoming: 24,
    damaged: 0,
    warehouse: 'BLR-STOCK',
    supplier: 'Kastoori Crafts',
    status: 'active',
    tag: null,
    hsnCode: '4420',
    gstRate: 12,
    giftOccasions: 'birthday,wedding,anniversary',
    giftRecipients: 'women',
    giftAgeMin: 16,
    giftAgeMax: null,
    giftTypes: 'home-decor,jewelry',
    giftInterests: 'jewelry,organizing,keepsake',
  },
  {
    id: 'p4',
    name: 'Teddy Bear Plush 12"',
    sku: 'CDL-TOY-030',
    barcode: '8901111000042',
    category: 'Toys',
    brand: 'Cuddle Co',
    price: 799,
    cost: 340,
    stock: 64,
    reserved: 6,
    incoming: 100,
    damaged: 2,
    warehouse: 'BLR-STORE',
    supplier: 'Kastoori Crafts',
    status: 'active',
    tag: 'Kids favourite',
    hsnCode: '9503',
    gstRate: 12,
    giftOccasions: 'birthday,valentines,baby-shower',
    giftRecipients: 'kids,women',
    giftAgeMin: 1,
    giftAgeMax: 60,
    giftTypes: 'toys',
    giftInterests: 'cuddly,soft-toys,cute',
  },
  {
    id: 'p5',
    name: 'Assorted Chocolate Hamper',
    sku: 'COC-CHO-021',
    barcode: '8901111000059',
    category: 'Chocolates',
    brand: 'Cocoa Grove',
    price: 1299,
    cost: 610,
    stock: 32,
    reserved: 4,
    incoming: 80,
    damaged: 0,
    warehouse: 'BLR-STORE',
    supplier: 'Cocoa Grove Foods',
    status: 'active',
    tag: 'Bestseller',
    hsnCode: '1806',
    gstRate: 18,
    giftOccasions: 'birthday,valentines,anniversary,thank-you,festival',
    giftRecipients: 'anyone',
    giftAgeMin: null,
    giftAgeMax: null,
    giftTypes: 'chocolates',
    giftInterests: 'chocolate,sweets,indulgence',
  },
  {
    id: 'p6',
    name: 'Personalized Ceramic Mug',
    sku: 'MUG-PRS-008',
    barcode: '8901111000066',
    category: 'Personalized',
    brand: 'MugMagic',
    price: 449,
    cost: 178,
    stock: 210,
    reserved: 0,
    incoming: 0,
    damaged: 3,
    warehouse: 'BLR-STOCK',
    supplier: 'Papertrail Studio',
    status: 'active',
    tag: null,
    hsnCode: '6912',
    gstRate: 12,
    giftOccasions: 'birthday,thank-you,farewell',
    giftRecipients: 'anyone',
    giftAgeMin: null,
    giftAgeMax: null,
    giftTypes: 'mug,personalized',
    giftInterests: 'coffee,tea,office',
  },
  {
    id: 'p7',
    name: 'Sandalwood Perfume Gift Set',
    sku: 'MYS-PRF-002',
    barcode: '8901111000073',
    category: 'Fragrance',
    brand: 'Mysore Naturals',
    price: 1999,
    cost: 940,
    stock: 24,
    reserved: 3,
    incoming: 40,
    damaged: 0,
    warehouse: 'BLR-STORE',
    supplier: 'Mysore Naturals',
    status: 'active',
    tag: 'Premium',
    hsnCode: '3303',
    gstRate: 18,
    giftOccasions: 'valentines,anniversary,birthday',
    giftRecipients: 'men,women',
    giftAgeMin: 16,
    giftAgeMax: null,
    giftTypes: 'perfume',
    giftInterests: 'fragrance,grooming,luxury',
  },
  {
    id: 'p8',
    name: 'Leather Bifold Wallet',
    sku: 'HID-WLT-015',
    barcode: '8901111000080',
    category: 'Accessories',
    brand: 'Hidesmith',
    price: 1199,
    cost: 520,
    stock: 0,
    reserved: 0,
    incoming: 120,
    damaged: 0,
    warehouse: 'BLR-STOCK',
    supplier: 'Kastoori Crafts',
    status: 'out',
    tag: null,
    hsnCode: '4202',
    gstRate: 12,
    giftOccasions: 'birthday,anniversary,farewell,thank-you',
    giftRecipients: 'men',
    giftAgeMin: 16,
    giftAgeMax: null,
    giftTypes: 'wallet',
    giftInterests: 'fashion,accessories,everyday',
  },
  {
    id: 'p9',
    name: 'Minimalist Wall Clock',
    sku: 'TCK-CLK-010',
    barcode: '8901111000097',
    category: 'Home Decor',
    brand: 'TickTock',
    price: 1099,
    cost: 470,
    stock: 12,
    reserved: 0,
    incoming: 0,
    damaged: 1,
    warehouse: 'HYD-STORE',
    supplier: 'Kastoori Crafts',
    status: 'active',
    tag: null,
    hsnCode: '9105',
    gstRate: 18,
    giftOccasions: 'housewarming,wedding,farewell',
    giftRecipients: 'anyone',
    giftAgeMin: null,
    giftAgeMax: null,
    giftTypes: 'home-decor',
    giftInterests: 'decor,home,minimalist',
  },
  {
    id: 'p10',
    name: 'Copper Fairy String Lights',
    sku: 'GLO-LGT-006',
    barcode: '8901111000103',
    category: 'Festive',
    brand: 'Glowveda',
    price: 399,
    cost: 150,
    stock: 180,
    reserved: 10,
    incoming: 200,
    damaged: 0,
    warehouse: 'BLR-STORE',
    supplier: 'Glowveda Lights',
    status: 'active',
    tag: 'Trending',
    hsnCode: '9405',
    gstRate: 12,
    giftOccasions: 'housewarming,festival,birthday',
    giftRecipients: 'anyone',
    giftAgeMin: null,
    giftAgeMax: null,
    giftTypes: 'home-decor',
    giftInterests: 'decor,festive,cozy',
  },
  {
    id: 'p11',
    name: 'Leather-bound Journal',
    sku: 'PAP-JRN-018',
    barcode: '8901111000110',
    category: 'Stationery',
    brand: 'Papertrail',
    price: 599,
    cost: 245,
    stock: 90,
    reserved: 2,
    incoming: 0,
    damaged: 0,
    warehouse: 'BLR-STOCK',
    supplier: 'Papertrail Studio',
    status: 'active',
    tag: null,
    hsnCode: '4820',
    gstRate: 12,
    giftOccasions: 'graduation,farewell,thank-you,birthday',
    giftRecipients: 'anyone',
    giftAgeMin: 12,
    giftAgeMax: null,
    giftTypes: 'stationery',
    giftInterests: 'writing,journaling,reading',
  },
  {
    id: 'p12',
    name: 'Ceramic Succulent Planter',
    sku: 'TER-PLN-003',
    barcode: '8901111000127',
    category: 'Plants',
    brand: 'Terra & Co',
    price: 349,
    cost: 132,
    stock: 8,
    reserved: 1,
    incoming: 60,
    damaged: 0,
    warehouse: 'HYD-STORE',
    supplier: 'Kastoori Crafts',
    status: 'low',
    tag: null,
    hsnCode: '6913',
    gstRate: 12,
    giftOccasions: 'housewarming,thank-you,birthday',
    giftRecipients: 'anyone',
    giftAgeMin: null,
    giftAgeMax: null,
    giftTypes: 'home-decor',
    giftInterests: 'plants,gardening,decor',
  },
  {
    id: 'p13',
    name: 'Silk Greeting Card Set',
    sku: 'PAP-CRD-025',
    barcode: '8901111000134',
    category: 'Stationery',
    brand: 'Papertrail',
    price: 249,
    cost: 88,
    stock: 320,
    reserved: 0,
    incoming: 0,
    damaged: 5,
    warehouse: 'BLR-STOCK',
    supplier: 'Papertrail Studio',
    status: 'active',
    tag: null,
    hsnCode: '4817',
    gstRate: 12,
    giftOccasions: 'birthday,thank-you,anniversary',
    giftRecipients: 'anyone',
    giftAgeMin: null,
    giftAgeMax: null,
    giftTypes: 'stationery',
    giftInterests: 'writing,cards,keepsake',
  },
  {
    id: 'p14',
    name: 'Analog Wrist Watch',
    sku: 'KRO-WCH-009',
    barcode: '8901111000141',
    category: 'Accessories',
    brand: 'Kronos',
    price: 2499,
    cost: 1180,
    stock: 15,
    reserved: 2,
    incoming: 30,
    damaged: 0,
    warehouse: 'BLR-STORE',
    supplier: 'Kastoori Crafts',
    status: 'active',
    tag: null,
    hsnCode: '9102',
    gstRate: 18,
    giftOccasions: 'birthday,anniversary,graduation',
    giftRecipients: 'men,women',
    giftAgeMin: 16,
    giftAgeMax: null,
    giftTypes: 'watch',
    giftInterests: 'fashion,accessories,style',
  },
  {
    id: 'p15',
    name: 'Scented Reed Diffuser',
    sku: 'AUR-DIF-014',
    barcode: '8901111000158',
    category: 'Fragrance',
    brand: 'Auraluxe',
    price: 749,
    cost: 320,
    stock: 40,
    reserved: 3,
    incoming: 0,
    damaged: 0,
    warehouse: 'BLR-STORE',
    supplier: 'Auraluxe Candles',
    status: 'active',
    tag: null,
    hsnCode: '3307',
    gstRate: 18,
    giftOccasions: 'housewarming,anniversary,thank-you',
    giftRecipients: 'women,anyone',
    giftAgeMin: null,
    giftAgeMax: null,
    giftTypes: 'perfume,home-decor',
    giftInterests: 'fragrance,relaxation,home',
  },
  {
    id: 'p16',
    name: 'Silver Pendant Necklace',
    sku: 'KAS-NEC-007',
    barcode: '8901111000165',
    category: 'Jewelry',
    brand: 'Kastoori',
    price: 1899,
    cost: 910,
    stock: 22,
    reserved: 2,
    incoming: 20,
    damaged: 0,
    warehouse: 'BLR-STORE',
    supplier: 'Kastoori Crafts',
    status: 'active',
    tag: 'New',
    hsnCode: '7113',
    gstRate: 3,
    giftOccasions: 'valentines,anniversary,birthday,wedding',
    giftRecipients: 'women',
    giftAgeMin: 14,
    giftAgeMax: null,
    giftTypes: 'jewelry',
    giftInterests: 'jewelry,fashion,silver',
  },
  {
    id: 'p17',
    name: 'Gourmet Tea Sampler Box',
    sku: 'CHB-TEA-011',
    barcode: '8901111000172',
    category: 'Gourmet',
    brand: 'Chai Bagh',
    price: 899,
    cost: 390,
    stock: 55,
    reserved: 1,
    incoming: 40,
    damaged: 0,
    warehouse: 'HYD-STORE',
    supplier: 'Cocoa Grove Foods',
    status: 'active',
    tag: null,
    hsnCode: '0902',
    gstRate: 5,
    giftOccasions: 'thank-you,housewarming,festival,farewell',
    giftRecipients: 'anyone',
    giftAgeMin: null,
    giftAgeMax: null,
    giftTypes: '',
    giftInterests: 'tea,wellness,gourmet',
  },
  {
    id: 'p18',
    name: 'Wooden Chess Set',
    sku: 'GRM-CHS-005',
    barcode: '8901111000189',
    category: 'Toys',
    brand: 'Grandmaster',
    price: 1599,
    cost: 720,
    stock: 0,
    reserved: 0,
    incoming: 40,
    damaged: 0,
    warehouse: 'BLR-STOCK',
    supplier: 'Kastoori Crafts',
    status: 'out',
    tag: null,
    hsnCode: '9504',
    gstRate: 12,
    giftOccasions: 'birthday,graduation,farewell',
    giftRecipients: 'men,kids,anyone',
    giftAgeMin: 8,
    giftAgeMax: null,
    giftTypes: 'toys',
    giftInterests: 'games,strategy,hobby',
  },
  {
    id: 'p19',
    name: 'Bamboo Desk Organizer',
    sku: 'TER-ORG-016',
    barcode: '8901111000196',
    category: 'Home Decor',
    brand: 'Terra & Co',
    price: 699,
    cost: 285,
    stock: 26,
    reserved: 0,
    incoming: 0,
    damaged: 1,
    warehouse: 'HYD-STORE',
    supplier: 'Papertrail Studio',
    status: 'active',
    tag: null,
    hsnCode: '4420',
    gstRate: 12,
    giftOccasions: 'graduation,farewell,thank-you,housewarming',
    giftRecipients: 'anyone',
    giftAgeMin: 14,
    giftAgeMax: null,
    giftTypes: 'home-decor',
    giftInterests: 'office,organizing,work',
  },
  {
    id: 'p20',
    name: 'Festive Diya Gift Set',
    sku: 'GLO-DYA-020',
    barcode: '8901111000202',
    category: 'Festive',
    brand: 'Glowveda',
    price: 549,
    cost: 210,
    stock: 140,
    reserved: 12,
    incoming: 100,
    damaged: 0,
    warehouse: 'BLR-STORE',
    supplier: 'Glowveda Lights',
    status: 'active',
    tag: 'Festive pick',
    hsnCode: '9405',
    gstRate: 12,
    giftOccasions: 'festival,housewarming',
    giftRecipients: 'anyone',
    giftAgeMin: null,
    giftAgeMax: null,
    giftTypes: 'home-decor',
    giftInterests: 'festive,diwali,decor',
  },
];

/* ---------------------------------------------------------------- product media
 * Every product has two photos; six featured products also have a short video.
 * Files are committed under apps/stockwell/public/seed/ and served statically. */
const FEATURED_VIDEO = new Set(['p1', 'p4', 'p5', 'p7', 'p10', 'p16']);
const PRODUCT_MEDIA = PRODUCTS.flatMap((p) => {
  const rows: {
    id: string;
    productId: string;
    url: string;
    type: string;
    sortOrder: number;
  }[] = [
    { id: `${p.id}m1`, productId: p.id, url: `/seed/${p.id}-a.jpg`, type: 'image', sortOrder: 0 },
    { id: `${p.id}m2`, productId: p.id, url: `/seed/${p.id}-b.jpg`, type: 'image', sortOrder: 1 },
  ];
  if (FEATURED_VIDEO.has(p.id)) {
    rows.push({
      id: `${p.id}m3`,
      productId: p.id,
      url: `/seed/${p.id}-vid.mp4`,
      type: 'video',
      sortOrder: 2,
    });
  }
  return rows;
});

/* ------------------------------------------------------------- engagement events
 * Synthetic Discover-reels engagement so the storefront (like/share counts) and
 * the admin Engagement dashboard look alive. Tagged/"popular" items get more. */
const SESSIONS = Array.from(
  { length: 40 },
  (_, i) => `sess-${(i + 1).toString().padStart(3, '0')}`,
);
const PRODUCT_EVENTS: { productId: string; type: string; sessionId: string }[] = [];
let _ev = 0;
const pushEvents = (productId: string, type: string, n: number) => {
  for (let i = 0; i < n; i++) {
    PRODUCT_EVENTS.push({ productId, type, sessionId: SESSIONS[_ev++ % SESSIONS.length] });
  }
};
for (const p of PRODUCTS) {
  if (p.status === 'out') continue; // only sellable items appear in Discover
  const popular = !!p.tag;
  const views = (popular ? 70 : 28) + ((p.id.charCodeAt(1) * 13) % 45);
  const likes = Math.round(views * (popular ? 0.3 : 0.15));
  const shares = Math.round(likes * 0.32);
  const buys = Math.round(likes * 0.14);
  pushEvents(p.id, 'view', views);
  pushEvents(p.id, 'like', likes);
  pushEvents(p.id, 'share', shares);
  pushEvents(p.id, 'buy', buys);
}

/* ------------------------------------------------------------------ customers */
const CUSTOMERS = [
  {
    id: 'c1',
    name: 'Infosys Gifting (Corporate)',
    type: 'business',
    email: 'gifting@infosys-corp.in',
    phone: '+91 80 2852 0001',
    address: 'Electronics City, Bengaluru',
    orders: 14,
    spend: 182400,
    lastOrder: 'Jul 16',
    balance: 24800,
    color: '#2c5e8a',
  },
  {
    id: 'c2',
    name: 'Priya Sharma',
    type: 'individual',
    email: 'priya.sharma@gmail.com',
    phone: '+91 98450 22119',
    address: 'Jubilee Hills, Hyderabad',
    orders: 6,
    spend: 8940,
    lastOrder: 'Jul 15',
    balance: 0,
    color: '#9a3a3a',
  },
  {
    id: 'c3',
    name: 'Rahul Mehta',
    type: 'individual',
    email: 'rahul.mehta@gmail.com',
    phone: '+91 99860 44521',
    address: 'Indiranagar, Bengaluru',
    orders: 3,
    spend: 4650,
    lastOrder: 'Jul 10',
    balance: 0,
    color: '#2a7d4f',
  },
  {
    id: 'c4',
    name: 'Lotus Wedding Planners',
    type: 'business',
    email: 'orders@lotusweddings.in',
    phone: '+91 80 4123 8890',
    address: 'Koramangala, Bengaluru',
    orders: 9,
    spend: 96200,
    lastOrder: 'Jul 14',
    balance: 12400,
    color: '#6b4e8a',
  },
  {
    id: 'c5',
    name: 'Ananya Reddy',
    type: 'individual',
    email: 'ananya.reddy@gmail.com',
    phone: '+91 90000 11223',
    address: 'Banjara Hills, Hyderabad',
    orders: 5,
    spend: 7320,
    lastOrder: 'Jul 13',
    balance: 0,
    color: '#a8761c',
  },
  {
    id: 'c6',
    name: 'Walk-in customer',
    type: 'individual',
    email: '',
    phone: '',
    address: 'Bengaluru',
    orders: 0,
    spend: 0,
    lastOrder: '—',
    balance: 0,
    color: '#8a5a36',
  },
  {
    id: 'c7',
    name: 'TechNova Pvt Ltd',
    type: 'business',
    email: 'admin@technova.in',
    phone: '+91 40 4455 6677',
    address: 'HITEC City, Hyderabad',
    orders: 7,
    spend: 64800,
    lastOrder: 'Jul 12',
    balance: 0,
    color: '#2c5e8a',
  },
  {
    id: 'c8',
    name: 'Vikram Singh',
    type: 'individual',
    email: 'vikram.singh@gmail.com',
    phone: '+91 98111 55667',
    address: 'MG Road, Bengaluru',
    orders: 2,
    spend: 2748,
    lastOrder: 'Jul 08',
    balance: 0,
    color: '#9a3a3a',
  },
];

/* ------------------------------------------------------------ purchase orders */
const PURCHASE_ORDERS = [
  {
    id: 'PO-3042',
    supplier: 'Cocoa Grove Foods',
    items: 6,
    total: 48800,
    status: 'shipped',
    eta: 'Jul 24',
    created: 'Jul 15',
  },
  {
    id: 'PO-3041',
    supplier: 'Glowveda Lights',
    items: 8,
    total: 30200,
    status: 'approved',
    eta: 'Jul 26',
    created: 'Jul 14',
  },
  {
    id: 'PO-3040',
    supplier: 'Auraluxe Candles',
    items: 5,
    total: 27600,
    status: 'received',
    eta: 'Jul 12',
    created: 'Jul 05',
  },
  {
    id: 'PO-3039',
    supplier: 'Mysore Naturals',
    items: 3,
    total: 37600,
    status: 'approved',
    eta: 'Jul 27',
    created: 'Jul 13',
  },
  {
    id: 'PO-3038',
    supplier: 'Kastoori Crafts',
    items: 7,
    total: 52400,
    status: 'draft',
    eta: '—',
    created: 'Jul 16',
  },
  {
    id: 'PO-3037',
    supplier: 'Papertrail Studio',
    items: 4,
    total: 14900,
    status: 'received',
    eta: 'Jul 09',
    created: 'Jul 02',
  },
];

/* --------------------------------------------------------------- sales orders */
const SALES_ORDERS = [
  {
    id: 'SO-5821',
    customer: 'Infosys Gifting (Corporate)',
    items: 40,
    total: 51960,
    status: 'fulfilled',
    payment: 'paid',
    date: 'Jul 16',
  },
  {
    id: 'SO-5820',
    customer: 'Lotus Wedding Planners',
    items: 24,
    total: 35760,
    status: 'packing',
    payment: 'partial',
    date: 'Jul 15',
  },
  {
    id: 'SO-5819',
    customer: 'Priya Sharma',
    items: 3,
    total: 2597,
    status: 'fulfilled',
    payment: 'paid',
    date: 'Jul 15',
  },
  {
    id: 'SO-5818',
    customer: 'TechNova Pvt Ltd',
    items: 20,
    total: 25980,
    status: 'shipped',
    payment: 'paid',
    date: 'Jul 12',
  },
  {
    id: 'SO-5817',
    customer: 'Ananya Reddy',
    items: 2,
    total: 2148,
    status: 'fulfilled',
    payment: 'paid',
    date: 'Jul 13',
  },
  {
    id: 'SO-5816',
    customer: 'Rahul Mehta',
    items: 4,
    total: 3446,
    status: 'pending',
    payment: 'unpaid',
    date: 'Jul 10',
  },
  {
    id: 'SO-5815',
    customer: 'Vikram Singh',
    items: 2,
    total: 2748,
    status: 'fulfilled',
    payment: 'paid',
    date: 'Jul 08',
  },
];

/* ---------------------------------------------------------------- stock moves */
const STOCK_MOVES = [
  {
    type: 'add',
    product: 'Copper Fairy String Lights',
    productId: 'p10',
    qty: 200,
    who: 'Rohan D.',
    warehouse: 'BLR-STORE',
    meta: 'PO-3041 received',
  },
  {
    type: 'sale',
    product: 'Assorted Chocolate Hamper',
    productId: 'p5',
    qty: -18,
    who: 'System',
    warehouse: 'BLR-STORE',
    meta: 'SO-5821 fulfilled',
  },
  {
    type: 'add',
    product: 'Vanilla Bean Soy Candle',
    productId: 'p1',
    qty: 60,
    who: 'Priya S.',
    warehouse: 'BLR-STORE',
    meta: 'PO-3040 received',
  },
  {
    type: 'sale',
    product: 'Personalized Ceramic Mug',
    productId: 'p6',
    qty: -24,
    who: 'System',
    warehouse: 'BLR-STOCK',
    meta: 'SO-5818 shipped',
  },
  {
    type: 'remove',
    product: 'Silk Greeting Card Set',
    productId: 'p13',
    qty: -5,
    who: 'Rohan D.',
    warehouse: 'BLR-STOCK',
    meta: 'Damaged in transit',
  },
  {
    type: 'sale',
    product: 'Festive Diya Gift Set',
    productId: 'p20',
    qty: -12,
    who: 'System',
    warehouse: 'BLR-STORE',
    meta: 'SO-5820 packing',
  },
  {
    type: 'add',
    product: 'Leather-bound Journal',
    productId: 'p11',
    qty: 40,
    who: 'Priya S.',
    warehouse: 'BLR-STOCK',
    meta: 'PO-3037 received',
  },
  {
    type: 'sale',
    product: 'Silver Pendant Necklace',
    productId: 'p16',
    qty: -3,
    who: 'System',
    warehouse: 'BLR-STORE',
    meta: 'SO-5819 fulfilled',
  },
  {
    type: 'add',
    product: 'Sandalwood Perfume Gift Set',
    productId: 'p7',
    qty: 20,
    who: 'Aarav M.',
    warehouse: 'BLR-STORE',
    meta: 'Stock count adjustment',
  },
];

/* ----------------------------------------------------------------------- team */
const USERS = [
  {
    id: 'u1',
    email: 'admin@stockwell.app',
    name: 'Aarav Menon',
    role: 'admin',
    active: 1,
    password: 'stockwell123',
  },
  {
    id: 'u2',
    email: 'owen@ridgemont.co',
    name: 'Aarav Menon',
    role: 'admin',
    active: 1,
    password: 'stockwell123',
  },
  {
    id: 'u3',
    email: 'priya@kanuka.store',
    name: 'Priya Sharma',
    role: 'staff',
    active: 1,
    password: 'stockwell123',
  },
  {
    id: 'u4',
    email: 'rohan@kanuka.store',
    name: 'Rohan Das',
    role: 'staff',
    active: 1,
    password: 'stockwell123',
  },
  {
    id: 'u5',
    email: 'meera@kanuka.store',
    name: 'Meera Iyer',
    role: 'staff',
    active: 0,
    password: 'stockwell123',
  },
];

/* ------------------------------------------------------------------- invoices */
const INVOICES = [
  {
    id: 'INV-7214',
    customer: 'Infosys Gifting (Corporate)',
    date: 'Jul 16, 2026',
    due: 'Aug 15, 2026',
    subtotal: 44034,
    tax: 7926,
    total: 51960,
    paid: 27160,
    status: 'partial',
    method: 'NEFT',
    channel: 'corporate',
    items: 3,
  },
  {
    id: 'INV-7213',
    customer: 'Lotus Wedding Planners',
    date: 'Jul 15, 2026',
    due: 'Aug 14, 2026',
    subtotal: 30305,
    tax: 5455,
    total: 35760,
    paid: 23360,
    status: 'partial',
    method: 'NEFT',
    channel: 'corporate',
    items: 4,
  },
  {
    id: 'INV-7212',
    customer: 'Priya Sharma',
    date: 'Jul 15, 2026',
    due: 'Jul 15, 2026',
    subtotal: 2201,
    tax: 396,
    total: 2597,
    paid: 2597,
    status: 'paid',
    method: 'UPI',
    channel: 'retail',
    items: 3,
  },
  {
    id: 'INV-7211',
    customer: 'TechNova Pvt Ltd',
    date: 'Jul 12, 2026',
    due: 'Aug 11, 2026',
    subtotal: 22017,
    tax: 3963,
    total: 25980,
    paid: 25980,
    status: 'paid',
    method: 'NEFT',
    channel: 'corporate',
    items: 2,
  },
  {
    id: 'INV-7210',
    customer: 'Ananya Reddy',
    date: 'Jul 13, 2026',
    due: 'Jul 13, 2026',
    subtotal: 1820,
    tax: 328,
    total: 2148,
    paid: 2148,
    status: 'paid',
    method: 'UPI',
    channel: 'retail',
    items: 2,
  },
  {
    id: 'INV-7209',
    customer: 'Rahul Mehta',
    date: 'Jul 10, 2026',
    due: 'Jul 25, 2026',
    subtotal: 2920,
    tax: 526,
    total: 3446,
    paid: 0,
    status: 'unpaid',
    method: '—',
    channel: 'retail',
    items: 4,
  },
  {
    id: 'INV-7208',
    customer: 'Vikram Singh',
    date: 'Jul 08, 2026',
    due: 'Jul 08, 2026',
    subtotal: 2329,
    tax: 419,
    total: 2748,
    paid: 2748,
    status: 'paid',
    method: 'Cash',
    channel: 'retail',
    items: 2,
  },
];

/* -------------------------------------------------------------------- returns */
const RETURNS = [
  {
    id: 'RMA-0142',
    customer: 'Infosys Gifting (Corporate)',
    invoice: 'INV-7180',
    items: 2,
    total: 1298,
    reason: 'Damaged',
    status: 'approved',
    date: 'Jul 14',
  },
  {
    id: 'RMA-0141',
    customer: 'Walk-in customer',
    invoice: 'INV-7156',
    items: 1,
    total: 449,
    reason: 'Changed mind',
    status: 'refunded',
    date: 'Jul 12',
  },
  {
    id: 'RMA-0140',
    customer: 'Ananya Reddy',
    invoice: 'INV-7149',
    items: 1,
    total: 899,
    reason: 'Wrong item',
    status: 'pending',
    date: 'Jul 11',
  },
  {
    id: 'RMA-0139',
    customer: 'Lotus Wedding Planners',
    invoice: 'INV-7133',
    items: 3,
    total: 1647,
    reason: 'Defective',
    status: 'refunded',
    date: 'Jul 06',
  },
];

/* ------------------------------------------------------------------- settings */
const SETTINGS = [
  { key: 'appName', value: 'Kalki Gifts n Kids Mart' },
  { key: 'brandInitial', value: 'K' },
  { key: 'accentColor', value: '#e23747' },
  { key: 'tagline', value: 'Gifts for every occasion' },
  { key: 'plan', value: 'Growth' },
  { key: 'seats', value: '6' },
  { key: 'companyName', value: 'Kalki Gifts n Kids Mart' },
  { key: 'currency', value: '₹' },
  { key: 'taxRate', value: '0.18' },
  { key: 'address', value: '24 MG Road, Bengaluru 560001' },
  { key: 'email', value: 'hello@kalkigifts.store' },
  { key: 'phone', value: '+919845012345' },
  { key: 'whatsapp', value: '+919845012345' },
  { key: 'lowStockThreshold', value: '10' },
];

async function seed() {
  console.log('Seeding database…');
  await db.delete(schema.productEvents);
  await db.delete(schema.productMedia);
  await db.delete(schema.stockMoves);
  await db.delete(schema.products);
  await db.delete(schema.salesOrders);
  await db.delete(schema.purchaseOrders);
  await db.delete(schema.customers);
  await db.delete(schema.suppliers);
  await db.delete(schema.warehouses);
  await db.delete(schema.users);
  await db.delete(schema.invoices);
  await db.delete(schema.returns);
  await db.delete(schema.settings);

  await db.insert(schema.warehouses).values(WAREHOUSES);
  await db.insert(schema.suppliers).values(SUPPLIERS);
  await db.insert(schema.products).values(PRODUCTS as any);
  await db.insert(schema.productMedia).values(PRODUCT_MEDIA as any);
  // events can be many — chunk to stay under SQLite's variable limit
  for (let i = 0; i < PRODUCT_EVENTS.length; i += 200) {
    await db.insert(schema.productEvents).values(PRODUCT_EVENTS.slice(i, i + 200) as any);
  }
  await db.insert(schema.customers).values(CUSTOMERS);
  await db.insert(schema.purchaseOrders).values(PURCHASE_ORDERS);
  await db.insert(schema.salesOrders).values(SALES_ORDERS);
  await db.insert(schema.stockMoves).values(STOCK_MOVES as any);
  await db.insert(schema.users).values(
    USERS.map((u) => ({
      id: u.id,
      email: u.email,
      name: u.name,
      role: u.role,
      active: u.active,
      passwordHash: hashPassword(u.password),
    })),
  );
  await db.insert(schema.invoices).values(INVOICES);
  await db.insert(schema.returns).values(RETURNS);
  await db.insert(schema.settings).values(SETTINGS);

  console.log(
    `✓ Seeded ${WAREHOUSES.length} stores, ${SUPPLIERS.length} suppliers, ${PRODUCTS.length} products, ${PRODUCT_MEDIA.length} media, ${PRODUCT_EVENTS.length} events, ${CUSTOMERS.length} customers, ${PURCHASE_ORDERS.length} POs, ${SALES_ORDERS.length} SOs, ${STOCK_MOVES.length} moves, ${USERS.length} users, ${INVOICES.length} invoices, ${RETURNS.length} returns`,
  );
  console.log(`  Admin login: admin@stockwell.app / stockwell123`);
  console.log(`  Staff login: priya@kanuka.store / stockwell123`);
  process.exit(0);
}
seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
